### ISSUE TITLE
Mongo connection error handling

### ISSUE THREAD

**Issue by pronebird** [donpark/session-mongoose#11]
Hi,

As I see, mongoose-session uses shared mongo connection if it's ready, otherwise it initiates a new one via mongoose.connect. So whenever mongodb is down my app just exits with unhandled exception. Would be cool to have an option to pass an error callback to session-mongoose. I see this change is very trivial, I am not a coffee expert :/ but it should be something like this:

```
// constructor
if typeof @options.callback is 'function'
    mongoose.connect @options.url, @options.callback
else
    mongoose.connect @options.url
```

Console output:

```
events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: failed to connect to [localhost:28000]
    at Server.connect.connectionPool.on.server._serverState (/Users/pronebird/dev/homejs/node_modules/session-mongoose/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:564:74)
    at EventEmitter.emit (events.js:126:20)
    at connection.on._self._poolState (/Users/pronebird/dev/homejs/node_modules/session-mongoose/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:124:15)
    at EventEmitter.emit (events.js:99:17)
    at Socket.errorHandler (/Users/pronebird/dev/homejs/node_modules/session-mongoose/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:465:10)
    at Socket.EventEmitter.emit (events.js:96:17)
    at Socket._destroy.self.errorEmitted (net.js:328:14)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)

```

**Comment by donpark** [comment]
Good suggestion. I don't remember seeing callback support in Mongoose when I first wrote this module.

Can't promise when this feature will be implemented though. :-(

**Comment by pronebird** [comment]
I can send you a pull request with the proposed code.

**Comment by pronebird** [comment]
Btw, I couldn't find error callback in mongoose docs, but after testing on latest mongoose, the last argument passed to mongoose.connect gets invoked with error argument in case of errors. e.g. http://stackoverflow.com/a/6680718/351305 and so far I see that's the only way to catch the error on connect.

**Comment by pronebird** [comment]
Well, it doesn't solve the problem completely. To suppress errors and let mongoose reconnect automatically to DB you have to:

1) Set error handler for any mongo errors, otherwise we end up with unhandled exception. `mongoose.connection.on('error', function (err) {});`
2) Pass error callback to `mongoose.connect(url, opts, function (err) {})`
3) Pass extra option to mongoose.connect `{ server: { auto_reconnect: true } }`

I think this issue requires more considerations. It can be easier just to allow passing mongoose (issue #9) with already setup connection rather than extending session-mongoose with unrelated stuff.

**Comment by donpark** [comment]
I agree.

Latest version of Mongoose simply passes `connect` call to `open` or `openSet` methods which does accept callback. `mongoose-session` was written when Mongoose didn't have callback in neither doc nor code. auto-reconnect wasn't supported either then.

I think the most flexible thing to do is expose custom mongoose configuration as an optional feature which will require some design-think time on my part.

Thanks for bringing up issues like this.
