### ISSUE TITLE
Use Mongo TTL instead of server-side session reapers

### ISSUE THREAD

**Issue by tommedema** [donpark/session-mongoose#18]
Using server-side sweepers is unreliable when operating a cluster. If one of the processes goes down, so will its reapers (workers) while the cluster remains active. The sessions related to that reaper won't be destroyed.

Instead use Mongo's TTL functionality, see http://docs.mongodb.org/manual/tutorial/expire-data/ for more information.

**Comment by pronebird** [comment]
That's awesome proposal.

**Comment by donpark** [comment]
Makes sense. I wasn't aware of Mongo TTL when this package was written but it's been available for awhile now so should be safe to add. I'll look into detecting feature available at run time also to maintain backward compatibility.

**Comment by donpark** [comment]
version 0.3.2 has experimental support for TTL. See README for info on how to enable it.
