### ISSUE TITLE
0.2.3+ doesn't work with sessions that never expire

### ISSUE THREAD

**Issue by airandfingers** [donpark/session-mongoose#20]
When I updated beyond 0.2.2, I noticed that my sessions were no longer persistent. Today, I tracked down the problem: session-mongoose 0.2.3 adds support for sweeping out expired sessions, and the query in its get function only gets sessions with an expires value >= now:

```
if @options.ttl > 0
    query = { sid: sid }
  else
    query = { sid: sid, expires: {'$gte': new Date()} }
```

This was a problem for me, since I wasn't setting a cookie.maxAge or cookie.expires value in my Express session code. My sessions had "expires" values of null, so the get function was never getting them.

I changed my code to have cookie.maxAge values to play nice with session-mongoose 0.2.3+, but session-mongoose should also work with sessions without expires values.

**Comment by pronebird** [comment]
I don't really see how this can be fixed. Maybe with default expiration value?

**Comment by donpark** [comment]
why not just set maxAge to some large value, say 5yrs?

**Comment by airandfingers** [comment]
I set the maxAge value, which solved this problem for me, but it's a workaround. Connect's/Express's default behavior is to set expires to null, and I don't think session-mongoose should dictate how users configure Connect/Express. If session-mongoose is going to require maxAge to be set, this should be explicitly stated in the docs.

As for how to fix this, why not just change the query to also match sessions without expires values?

```
if @options.ttl > 0
  query = { sid: sid }
else
  query = { sid: sid, $or: [ { expires: { '$gte': new Date() } }, { expires: { $exists: false } } ] }
```

From http://www.senchalabs.org/connect/session.html#session: 

```
Cookie option:

By default cookie.maxAge is null, meaning no "expires" parameter is set
so the cookie becomes a browser-session cookie. When the user closes the
browser the cookie (and session) will be removed.
```

**Comment by pronebird** [comment]
@airandfingers :+1: otherwise we have null-records in database that stuck there forever I guess. I remember quite some time ago I experienced the same and sessions were simply created on each request.

@donpark I guess it makes sense to handle such cases or at least fallback to some default expiration period in sake of data consistency.

**Comment by donpark** [comment]
@airandfingers, do you mind sending a pull request with changes as you suggested?

**Comment by airandfingers** [comment]
@donpark Sure thing. Do you have a process for testing before I send the request in, or should I just test it by hand and leave the rest to you?

**Comment by donpark** [comment]
no unfortunately. if you haven't tested your changes, we should wait
until one of us has time to do so.

**Comment by airandfingers** [comment]
I can definitely test my changes by hand (make sure it still works with non-null expires values, as well as null expires values, and still sweeps out expired sessions), but I'm asking if I need to run the tests you've already written, and/or write tests of my own. I see that "npm test" will run your existing tests; I guess I'll do that as a minimum.

**Comment by airandfingers** [comment]
A couple notes:

My changes don't exactly match what I pasted before; apparently null values don't match the { $exists: false } query, so I used { expires: null } instead.

I've tested this by hand with both never-expiring sessions with null expires values and sessions that expire after 1 hour.
