### ISSUE TITLE
Do not allow the same user to be logged on more than one device.

### ISSUE THREAD

**Issue by pavelnikolov** [donpark/session-mongoose#23]
I have an invite-only application and I do not want a single user to be able to share his username and password to multiple users. When an user is logged in from one device and then his username/password are used on another device I want the session on the first one to be invalidated/removed. Basically every time when an user logs in I want all session of that user to be invalidated/removed.

**Comment by donpark** [comment]
@pavelnikolov imo this functionality belongs at the app-level,
not at session storage implementation level.

Your app should maintain account to session mapping then
clear out any session other than current one.

**Comment by pavelnikolov** [comment]
Thanks for your suggestion. You are correct and it actually required just a single line of code
`Session.remove({ 'data.passport.user': user._id }, function(err) { return done(err, user); })`
in my `deserialize` method to work.
