### ISSUE TITLE
NodeJS Express session variable not saved when using jQuery POST

### ISSUE THREAD

**Issue by cmoreno** [donpark/session-mongoose#25]
I found an issue with session and storing variables. I described the issue in detail here:

http://stackoverflow.com/questions/25273840/nodejs-express-session-variable-not-saved-when-using-jquery-post/25274452?noredirect=1#comment39415662_25274452

**Comment by donpark** [comment]
Hi. On which versions of Node, Express, and Mongoose are you running into this issue?

**Comment by cmoreno** [comment]
I am using the following:

Node: v0.10.31
Express: 3.1.0
Mongoose: 3.9.1 (I just realized this is an experimental version of Mongoose)

**Comment by donpark** [comment]
Bad news. Turns out latest versions of connect and express are not compatible with this module. With latest version, unit tests won't even run.

I currently have no plan to support latest versions because it would be simpler to create a new module than trying fix this 'old house'. Sorry.
