### ISSUE TITLE
"session-mongoose" strictly requires older version of "connect" to be installed

### ISSUE THREAD

**Issue by teamnorge** [donpark/session-mongoose#26]
I just noticed, that session-mongoose requires connect@ˆ2.0 in its package.json peerDependencies section.
Current version of "connect" is 3.3.3, so this usually caused to "The package does not satisfy its siblings' peerDependencies requirements!" error while upgrading.

**Comment by donpark** [comment]
I know. Currently there is no plan to support latest version of `connect` because, given how small simple this module is, it's easier to write a new module than try to support both 2.x and 3.x+ version of connect.
