### ISSUE TITLE
remember me

### ISSUE THREAD

**Issue by panosru** [donpark/session-mongoose#3]
Hello, great module, thanks for this!

Could you provide an example of remember me mechanism? For example, how can I modify store interval after user log's in?

**Comment by donpark** [comment]
Hi,

Store interval impacts all users in context of non-persistent sessions and is in no way related to authentication features like Remember Me.

 Most common way to implement Remember Me is to issue a permanent cookie containing a verifiable token. When user revisits, check the token then create authorized session. Token should be something like HMAC(username+salt).

**Comment by panosru** [comment]
@donpark Hello! Thanks for the tip :)
