### ISSUE TITLE
Connect dependency

### ISSUE THREAD

**Issue by pronebird** [donpark/session-mongoose#8]
Hi, I use Express 3.0.3 and session-mongoose, today I decided to update all packages, ran npm update and when I re-ran my app I got the following error:

``` module.js:340
    throw err;
          ^
Error: Cannot find module 'connect'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/home/user/homejs/node_modules/session-mongoose/index.js:173:6)
    at Object.<anonymous> (/home/user/homejs/node_modules/session-mongoose/index.js:179:4)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

I looked through the latest changes for session-mongoose and I see you removed connect from dependencies, can you please elaborate why you did it if actual code depends on connect presence?

**Comment by donpark** [comment]
I removed `connect` dependency because `session-mongoose` is a `connect` plugin. Default npm dependency is implementation dependency. If npm supported _environmental_ dependency, I could use that but, as-is, having `connect` as plain dependency will likely result in multiple instances of connect.

I am thinking about adding connect instance as an argument to SessionStore constructor. This is how `connect-redis` handles the same dependency issue.

**Comment by pronebird** [comment]
Good point, agree about passing connect to session-mongoose, seems like the most appropriate way so far.

**Comment by donpark** [comment]
Thanks. Actually, it's not SessionStore constructor but _module constructor_ of sort which is used like this:

```
    var SessionStore = require('session-mongoose')(connect);
```

which will break backward-compatibility. I'll have to try some tricks to not do that.

**Comment by donpark** [comment]
version 0.2 implements what I describe above.

Unfortunately this breaks older code. I thought I could avoid this but could not find a workable solution without causing bigger trouble down the road.

My apologies.
